### ISSUE TITLE
getMemory function does not adhere to PEP-8 style guide

### ISSUE THREAD

**Issue by camielverdult** [AM2i9/GDStatusBot#2]
The code in [this](https://github.com/AM2i9/GDStatusBot/blob/master/main.py#L249-L258) function does not adhere to the PEP-8 style guide.

Please read this: https://www.python.org/dev/peps/pep-0008/ and go to the section about try/except clauses. (This part:) 
```py
# Correct:
try:
    value = collection[key]
except KeyError:
    return key_not_found(key)
else:
    return handle_value(value)
```

**Comment by camielverdult** [comment]
Oh and BTW - your website has a spelling error "ammount"

**Comment by AM2i9** [comment]
> Oh and BTW - your website has a spelling error "ammount"

I genuinely wonder how I've never noticed that lol
